# Generated by Django 5.0.7 on 2026-03-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(default='custom', max_length=10)),
                ('ai_pipeline_id', models.IntegerField(blank=True, null=True)),
                ('preprocessing', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_engineering', models.CharField(blank=True, max_length=100, null=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('postprocessing', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='datasets.dataset')),
            ],
        ),
    ]
