# Generated by Django 5.0.7 on 2026-03-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='best_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='optimization_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
