# Generated by Django 5.0.7 on 2026-03-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingjob_best_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='feature_columns',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
