# Generated by Django 5.0.7 on 2026-03-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_feature_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('optimizing', 'Optimizing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
