# Generated by Django 5.0.7 on 2026-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_add_optimizing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='hyperparams',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='n_clusters',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='target_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='test_size',
            field=models.FloatField(default=0.2),
        ),
    ]
