# Generated by Django 5.0.7 on 2026-04-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0001_initial'),
        ('training', '0006_add_image_zip_path_nullable_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='results.usersession'),
        ),
    ]
