from django.urls import path
from .views import (
    ping,
    save_description,
    dataset_columns,
    upload_dataset,
    upload_drive_csv,
    analyze_dataset,
    recommend_pipelines,
    train_model,
    get_training_result,
    cancel_job,
    optimize_model,
    export_model,
    clear_cache,
    upload_image_zip,
    start_image_clustering,
    image_from_drive,
    download_image_clusters,
    user_sessions,
)

urlpatterns = [
    path("ping/", ping, name="ping"),
    path("describe/<int:dataset_id>/", save_description, name="describe"),
    path("columns/<int:dataset_id>/", dataset_columns, name="columns"),
    path("upload/", upload_dataset, name="upload"),
    path("upload-drive/", upload_drive_csv, name="upload_drive"),
    path("analyze/<int:dataset_id>/", analyze_dataset, name="analyze"),
    path("recommend/<int:dataset_id>/", recommend_pipelines, name="recommend"),
    path("train/", train_model, name="train"),
    path("result/<int:job_id>/", get_training_result, name="result"),
    path("cancel/<int:job_id>/", cancel_job, name="cancel_job"),
    path("optimize/", optimize_model, name="optimize"),
    path("export/<int:job_id>/<str:fmt>/", export_model, name="export"),
    path("clear-cache/", clear_cache, name="clear_cache"),
    path("image-upload/", upload_image_zip, name="image_upload"),
    path("image-cluster/", start_image_clustering, name="image_cluster"),
    path("image-drive/", image_from_drive, name="image_drive"),
    path("image-download/<int:job_id>/", download_image_clusters, name="image_download"),
    path("user-sessions/", user_sessions, name="user_sessions"),
]

